### ISSUE TITLE
Extendable errors?

### ISSUE THREAD

**Issue by nickclaw** [yanickrochon/error-factory#2]
It would be really useful to be able to create new custom error types that extend other custom error types. Something like:

```javascript
var CustomError = errorFactory('CustomError', ['message', 'data']);
var SpecialCustomError = CustomError.extend('SpecialCustomError', ['flag']);

var error = new SpecialCustomError('there was an error', {}, false);
console.log(error instanceof CustomError); // true
console.log(error.message); // "there was an error"
console.log(error.data); // {}
console.log(error.flag); // false
```

Any chance that could fit into this module? I looked into adding it myself but it looks like it's not compatible with it currently because you create the error constructors with a string, and I wanted to check in before wasting my time on incompatible pull requests.

**Comment by yanickrochon** [comment]
I will take a look at it tonight. I haven't touched this module in a few months, but I am sure the prototypes generated (even using a string) are compatible with such feature.

Just a point of clarification, when extending a custom error type, in your example, `['flag']` is *adding* a third argument to the constructor, as if you had declared the type as 

```js
var SpecialCustomError = errorFactory('SpecialCustomError', ['message', 'data', 'flag']);
```

right?

**Comment by nickclaw** [comment]
That was my idea. Not sure if it's the best way though..

**Comment by yanickrochon** [comment]
I think it would get confusing, especially when you can declare a prototype with an object, or array, and there are the `ErrorProperty`, too. Normally, extending something assume that the super constructor will be called with the declared arguments, regardless of the constructor's signature. For example :

```js
var CustomError = errorFactory('CustomError', ['message', 'data']);
var SpecialCustomError = CustomError.extend('SpecialCustomError', ['flag']);
```

When creating `SpecialCustomError(false)`, the super constructor (i.e. `CustomError`) should get called like `CustomError(undefined, undefined)` since these are not defined in the extending prototype. It may seem redundant to requiring the same signature for `SpecialCustomError` adding the `flag` argument definition, but it's the only way to have a flexible, and simple implementation.

**Comment by yanickrochon** [comment]
@nickclaw is that implementation working for your requirements?

**Comment by nickclaw** [comment]
Yes this looks great! Being able to `instanceof` is huge for me. Is it correct to assume that errors will inherit their base classes methods?

**Comment by yanickrochon** [comment]
Yes, they should, since I'm using the actual `util.inherits(CustomError, baseType || Error);` to extend, therefore any method from the base prototype will be available in the custom error type also. As long as these methods are set unto the `baseType`'s prototype.

**Comment by nickclaw** [comment]
Just wanted to mention that this is working perfectly for me in my repo [nickclaw/vlad#errors](https://github.com/nickclaw/vlad/tree/errors) branch. Unless you don't think it's ready yet could you publish it on npm?

**Comment by yanickrochon** [comment]
Done!

**Comment by nickclaw** [comment]
Thanks a bunch!
